import React from 'react';
import { render } from '@testing-library/react';
import RootLayout, { metadata } from '@/app/layout';

describe('RootLayout', () => {
    it('renders children correctly', () => {
        const { getByText } = render(
            <RootLayout>
                <div>Test Child</div>
            </RootLayout>
        );
        expect(getByText('Test Child')).toBeInTheDocument();
    });

    it('applies antialiased class to the body', () => {
        render(
            <RootLayout>
                <div>Test Child</div>
            </RootLayout>
        );
        const body = document.body;
        expect(body).toHaveClass('antialiased');
    });

    it('sets the correct metadata', () => {
        expect(metadata.title).toBe('Create Next App');
        expect(metadata.description).toBe('Generated by create next app');
    });
});
